config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  root "homes#top"
  get "/home/about" => "homes#about"
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  attachment :profile_image
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }      
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about,:show, :index]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  def after_sign_out_path_for(resource)
     root_path
  end 
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end 

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end




class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about, :public_action]
  before_action :configure_permitted_parameters,if: :devise_controller?

    def after_sign_out_path_for(resource)
      root_path
    end

    def after_sign_in_path_for(resource)
	    user_path(resource)
    end

   
  	def configure_permitted_parameters
  	  devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def create
     if flash[:notice]
     end 
  end 

  def index
  end
  
  def show
  end 
  
  def edit
  end
  
  def update
    if flash[:notice]
    end
  end 
  
  def destroy
  end 

  private
  def book_params
  end 
  # def correct_user
  # if 
  # end
  # end 
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end 
  
  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # def create
  #   @user = User.new(user_params)
  #   @user.user_id = current.id
  #   @user.save
  #   redirect_to user_path
  # end

  def index
  end

  def show
  end

  def edit
    # if
    # end 
  end 

  def update
    if flash[:notice]
    end
  end
  
  
  private
  
  def user_params
  end 
  
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<h1>Books</h1>

app/views/homes/about.html.erb
<h1>Welcome to Bookers!</h1>

app/views/homes/top.html.erb
<h1>welcome to bookers!!</h1>
<h3>in Bookers,</h3>
you can share and exchange your opinions , inpressions , and emotions</br>
about various books!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "Users", users_path %>
      </li>
      <li>
        <%= link_to "Books", books_path %>
      </li>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "About", home_about_path %>
      </li>
      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log in", new_user_session_path %>
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>